source 'https://rubygems.org'

  gem 'selenium-webdriver'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'pry'
  gem 'pry-remote'
  gem 'require_all'
  gem 'yaml_extend'
  gem 'parallel_tests'
  gem 'cucumber', '~> 3.1', '>= 3.1.2'
  gem 'allure-cucumber', "~> 0.6.1"
  gem 'faker'
  gem 'rake' , '>= 0.9.2'
  gem 'logger', '~> 1.3.0'
  gem 'git'
  gem 'rest-client'
  # gem 'byebug', platform: [:mri, :mingw, :x64_mingw]
  gem 'webdriver_manager'
  gem 'teber-library'